const {test} = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {execFileSync} = require('node:child_process');
const manifest = require('../scripts/project_manifest.cjs');
test('manifest preserves exact blobs, modes, deletes and committed tree; dirty work fails', t => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'panack-manifest-'));
  t.after(() => fs.rmSync(cwd, {recursive: true, force: true}));
  const git = (...args) => execFileSync('git', args, {cwd}).toString().trim();
  git('init', '-q'); git('config', 'user.name', 'Test'); git('config', 'user.email', 'test@example.invalid');
  fs.writeFileSync(path.join(cwd, 'remove'), 'old'); git('add', '.'); git('commit', '-qm', 'base');
  const base = git('rev-parse', 'HEAD');
  fs.unlinkSync(path.join(cwd, 'remove'));
  const bytes = Buffer.from([0, 255, 10, 65]); fs.writeFileSync(path.join(cwd, 'binary file'), bytes);
  fs.writeFileSync(path.join(cwd, 'tool'), '#!/bin/sh\n'); fs.chmodSync(path.join(cwd, 'tool'), 0o755);
  git('add', '.'); git('commit', '-qm', 'change');
  const options = {cwd, repository: 'owner/repo', branch: 'chore/tools', base, message: 'Publish'};
  const value = manifest(options);
  assert.equal(value.tree, git('rev-parse', 'HEAD^{tree}')); assert.equal(value.parentSha, base);
  assert.deepEqual(Buffer.from(value.files.find(file => file.path === 'binary file').content, 'base64'), bytes);
  assert.equal(value.files.find(file => file.path === 'tool').mode, '100755');
  assert.equal(value.files.find(file => file.path === 'remove').sha, null);
  assert.throws(() => manifest({...options, branch: 'main'}), /feature branch/);
  fs.writeFileSync(path.join(cwd, 'untracked'), 'pending');
  assert.throws(() => manifest(options), /commit all changes/);
  fs.unlinkSync(path.join(cwd, 'untracked'));
  fs.symlinkSync('tool', path.join(cwd, 'link')); git('add', '.'); git('commit', '-qm', 'link');
  assert.throws(() => manifest(options), /unsupported file mode/);
});
